name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hydro-build
    paths:
      - "Dockerfile.template"
      - ".github/workflows/build.yml"
      - "rootfs/**"

env:
  DOCKER_BUILDKIT: 1
  COSIGN_EXPERIMENTAL: 1

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  php80:
      name: 8.0
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: "lab:latest"
            driver: cloud
            endpoint: "shopware/default"
  
        - uses: docker/build-push-action@v5
          with:
            tags: ghcr.io/shopware/docker-base-hydro:8.0.28
            context: "8.0"
            platforms: linux/amd64,linux/arm64
            push: true
            provenance: false
  
  php81:
      name: 8.1
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: "lab:latest"
            driver: cloud
            endpoint: "shopware/default"
  
        - uses: docker/build-push-action@v5
          with:
            tags: ghcr.io/shopware/docker-base-hydro:8.1.24
            context: "8.1"
            platforms: linux/amd64,linux/arm64
            push: true
            provenance: false
  
  php82:
      name: 8.2
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: "lab:latest"
            driver: cloud
            endpoint: "shopware/default"
  
        - uses: docker/build-push-action@v5
          with:
            tags: ghcr.io/shopware/docker-base-hydro:8.2.11
            context: "8.2"
            platforms: linux/amd64,linux/arm64
            push: true
            provenance: false
  
  php83:
      name: 8.3
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: "lab:latest"
            driver: cloud
            endpoint: "shopware/default"
  
        - uses: docker/build-push-action@v5
          with:
            tags: ghcr.io/shopware/docker-base-hydro:8.3.0RC5
            context: "8.3"
            platforms: linux/amd64,linux/arm64
            push: true
            provenance: false
  